apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nautilus
  labels:
    app: nautilus
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nautilus
  labels:
    app: nautilus
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/bcgov/nautilus-hackathon-2026.git"
      ref: openshift
    contextDir: nautilus
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: ./Dockerfile-Openshift
  output:
    to:
      kind: ImageStreamTag
      name: nautilus:latest
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
  runPolicy: Serial
