FROM rust:1.85-bookworm AS builder
RUN apt-get update \
    && apt-get install -y --no-install-recommends sqlite3 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . ./nautilus
WORKDIR /app/nautilus
RUN cargo install sqlx-cli --no-default-features --features sqlite
RUN make db-touch \
    && make db-migrate \
    && make db-seed
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl git libssl3 \
    && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz \
    | tar -xz -C /tmp \
    && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
    && rm -rf /tmp/linux-amd64
RUN curl -fsSL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.15.7/openshift-client-linux-4.15.7.tar.gz \
    | tar -xz -C /tmp \
    && mv /tmp/oc /usr/local/bin/oc \
    && rm -rf /tmp/kubectl /tmp/oc \
    && mkdir /.kube \
    && chmod 0777 /.kube
WORKDIR /app
COPY --from=builder /app/nautilus/target/release/nautilus /app/nautilus
COPY --from=builder /app/nautilus/nautilus.db /app/nautilus.db
COPY --from=builder /app/nautilus/templates /app/templates
RUN chmod 0666 /app/nautilus.db
CMD ["/bin/sh", "-c", "/app/nautilus api; tail -f /dev/null"]
